name: Build and Deploy
on:
  push:
    branches:
      #   - master
      - development
      #   - staging

env:
  AWS_REGION: ap-east-1

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: |
          if [ "${{ github.ref }}" == "refs/heads/development" ]; then
            npm run dev
          else
            npm run build
          fi

      #   TODO: We don't have any tests for now
      #   - name: Run Tests
      #     run: npm run test

      - name: Run Formatter
        run: npm run format

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: vite-build-files
          path: ./dist
  deploy:
    environment: ${{ github.ref == 'refs/heads/master' && 'production' ||
      github.ref == 'refs/heads/development' && 'development' ||
      github.ref == 'refs/heads/staging' && 'staging' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: build
    steps:
      # Download the build artifact
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-build-files

      # Setup the AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      # Copy the files from /build to S3 bucket based on the branch
      - name: Deploy static site to S3 bucket
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            aws s3 sync . s3://admin.pfunstore.com --delete
          elif [ "${{ github.ref }}" == "refs/heads/development" ]; then
            aws s3 sync . s3://development.admin.pfunstore.com --delete
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            aws s3 sync . s3://staging.admin.pfunstore.com --delete
          fi

      # Invalidate index file in Cloudfront (this forces edges to fetch the latest index.html)
      - name: Invalidate
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/index.html'
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
